### ISSUE TITLE
Missing "Enter/Leave" giveaway button after sync owned/wish/ignored games

### ISSUE THREAD

**Issue by k0nk** [JustArchi/ESGST#1]
Hi!

I have been using your script for a while and yesterday a noticed that the "Enter/Leave" giveaway button was missing and I didn't know why.

Today I did could replicate the issue:

1. Activate "Enter / Leave Giveaway Button" (click "Save Changes", refresh the page and see that the button is created).
2. Now sync "Owned/Wishlisted/Ignored Games" (click "Save Changes" 2x to close all popups, refresh the page, and the "Enter/Leave" button is gone).

Can you fix this?

Thanks in advance!

**Comment by JustArchi** [comment]
All matters that are not related to A-ESGST fork but rather to ESGST should be reported in original script's repo: https://github.com/rafaelgssa/esgst
