### ISSUE TITLE
Script Name Change

### ISSUE THREAD

**Issue by DieNastie** [JustArchi/ESGST#3]
As of a recent update the original ESGST got yet another questionable change so i decided to come back to ur fork despite it being script only.

My issue is that im not sure if this ur fork of the script or not because i dont see any AESGST in the code description. I followed the link from the SG thread.

Could you change the name?

**Comment by JustArchi** [comment]
Sure thing, I want to keep the changes done to the fork to the minimum so we keep compatibility with original ESGST, but I don't see anything wrong in adding a small adnotation to the name.

BTW, if you find some original ESGST change questionable and would like me to evaluate whether something can be done about it, let me know in standalone issue.

**Comment by JustArchi** [comment]
The change above will be effective in around ~15h when my CI provides automatic build. Starting then you should see the name as *Enhanced SteamGifts & SteamTrades fork by JustArchi (A-ESGST)*
