### ISSUE TITLE
Several bugs in ESGST

### ISSUE THREAD

**Issue by 10522** [JustArchi/ESGST#5]
@JustArchi, сan you please fix [this](https://github.com/rafaelgomesxyz/esgst/pull/1793), [this](https://github.com/rafaelgomesxyz/esgst/pull/1760#issuecomment-1960687136) and this (in the screenshot) bug?

![3231424](https://github.com/JustArchi/ESGST/assets/59209149/fd09307f-71a2-4dde-b428-2d43fe6989fe)

**Comment by JustArchi** [comment]
I've merged the PR you've linked as that looked justified to me. I'm not however fixing ESGST bugs, that's far out of the scope of this project - I'm only considering active hindrances from Rafael and bugfixes in form of PRs ready for review and inclusion into the project.

Thanks! You can update the userscript to get the fix up.
